SibersTestTask/Controllers/AddController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SibersTestTask.Models;
using SibersTestTask.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SibersTestTask.Controllers
{
    public class AddController : Controller
    {
        public ProjectContext db;
        public AddController(ProjectContext context)
        {
            db = context;
        }

        //Добавления нового проекта в бд
        #region AddProject
        public IActionResult AddProject()
        {
            ViewBag.Employees = db.Employees.ToList();
            return View();
        }
        [HttpPost]
        public IActionResult AddProject(Project project)
        {
            //Добавление руководителя в сотрудников проекта
            Employee director = db.Employees.Find(project.DirectorId);
            project.Employees.Add(director);

            //Добавление проекта в бд
            db.Projects.Add(project);
            db.SaveChanges();
            return RedirectToRoute(new { Controller = "Home", Action = "Projects" });
        }
        #endregion

        //Добавление нового сотрудника в бд
        #region AddEmployee
        public IActionResult AddEmployee()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddEmployee(Employee employee)
        {
            db.Employees.Add(employee);
            db.SaveChanges();
            return RedirectToRoute(new { Controller = "Home", Action = "Employees" });
        }
        #endregion

        //Добавление сотрудника в проект
        public IActionResult AddEmployeeProject(int idProject, int[] selectedEmployees)
        {
            Project newProject = db.Projects.Find(idProject);

            if(selectedEmployees != null)
            {
                foreach(var employee in db.Employees.Where(e => selectedEmployees.Contains(e.Id)))
                {
                    newProject.Employees.Add(employee);
                }
            }

            db.Entry(newProject).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToRoute(new { Controller = "Details", Action = "DetailsProject", id = newProject.Id });
        }
    }
}

SibersTestTask/Controllers/DeleteController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SibersTestTask.Models;
using SibersTestTask.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SibersTestTask.Controllers
{
    public class DeleteController : Controller
    {
        public ProjectContext db;
        public DeleteController(ProjectContext context)
        {
            db = context;
        }

        //Удвление проекта из бд
        public IActionResult DeleteProject(int id)
        {
            Project project = db.Projects.Find(id);

            db.Entry(project).State = EntityState.Deleted;
            db.SaveChanges();

            return RedirectToRoute(new { Controller = "Home", Action = "Projects" });
        }

        //Удаление сотрудника из проекта
        public IActionResult DeleteProjectTeam(int idProject, int idEmployee)
        {
            Project project = db.Projects.Include(t => t.Teams).FirstOrDefault(p => p.Id == idProject);
            Employee employee = db.Employees.FirstOrDefault(e => e.Id == idEmployee);

            if(project != null && employee != null)
            {
                var projectEmployee = project.Teams.FirstOrDefault(pe => pe.EmployeeId == employee.Id);
                project.Teams.Remove(projectEmployee);
                db.SaveChanges();
            }

            return RedirectToRoute(new { Controller = "Details", Action = "DetailsProject", id = idProject });
        }

        //Удаление сотрудника из бд
        public IActionResult DeleteEmployee(int id)
        {
            Employee employee = db.Employees.Find(id);

            db.Entry(employee).State = EntityState.Deleted;
            db.SaveChanges();

            return RedirectToRoute(new { Controller = "Home", Action = "Employees" });
        }
    }
}

SibersTestTask/Controllers/DetailsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SibersTestTask.Models;
using SibersTestTask.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SibersTestTask.Controllers
{
    public class DetailsController : Controller
    {
        public ProjectContext db;
        public DetailsController(ProjectContext context)
        {
            db = context;
        }

        //Содержимое проекта
        public IActionResult DetailsProject(int id)
        {
            Project project = db.Projects.Include(c => c.Employees).FirstOrDefault(p => p.Id == id);

            if (project != null)
            {
                List<Employee> employees = new List<Employee>();

                //Нахождение сотруников, которых нет в проекте и занесение их в ViewBag
                //В представлении через ViewBag эти сотрудники выводятся, чтобы можно было добавлять новых сотрудников в проект
                bool emp = false;
                foreach (var dbEmployee in db.Employees.ToList())
                {
                    foreach (var team in project.Teams.ToList())
                        if ((team.ProjectId == project.Id) && (team.EmployeeId == dbEmployee.Id))
                            emp = true;

                    if (emp == false)
                        employees.Add(dbEmployee);
                    else
                    emp = false;
                }
                ViewBag.Employees = employees;
                
                return View(project);
            }
            return NotFound();
        }

        //Детали сотрудника
        public IActionResult DetailsEmployee(int id)
        {
            Employee employee = db.Employees.Find(id);

            if (employee != null)
            {
                return View(employee);
            }
            return NotFound();
        }
    }
}

SibersTestTask/Controllers/EditController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SibersTestTask.Models;
using SibersTestTask.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SibersTestTask.Controllers
{
    public class EditController : Controller
    {
        public ProjectContext db;
        public EditController(ProjectContext context)
        {
            db = context;
        }

        //Редактирование данных проекта
        #region EditProject
        [HttpGet]
        public IActionResult EditProject(int id)
        {
            Project project = db.Projects.Include(t => t.Teams).FirstOrDefault(p => p.Id == id); ;

            List<Employee> employees = new List<Employee>();

            //Нахождение сотрудников, которых нет в проекте, кроме нынешнего руководителя, и занесение их в ViewBag
            //В представлении через ViewBag этих сотрудников можно выбирать как нового руководителя
            bool emp = false;
            foreach (var dbEmployee in db.Employees.ToList())
            {
                foreach (var team in project.Teams.ToList())
                    if ((team.ProjectId == project.Id) && (team.EmployeeId == dbEmployee.Id))
                        emp = true;

                if (emp == false)
                    employees.Add(dbEmployee);
                else
                    emp = false;
            }
            employees.Add(db.Employees.Find(project.DirectorId));
            ViewBag.Employees = employees;

            return View(project);
        }
        [HttpPost]
        public IActionResult EditProject(Project project, int idDirector)
        {
            //Добавление нового руководителя в проект
            Employee director = db.Employees.Find(project.DirectorId);
            project.Employees.Add(director);
            db.Entry(project).State = EntityState.Modified;

            //Нахождение изменённого проект и старого руководителя
            project = db.Projects.Include(t => t.Teams).FirstOrDefault(p => p.Id == project.Id);
            Employee employee = db.Employees.FirstOrDefault(e => e.Id == idDirector);
            
            //Удаление староого руководителя из проекта
            var oldDirector = project.Teams.FirstOrDefault(pe => pe.EmployeeId == employee.Id);
            project.Teams.Remove(oldDirector);

            db.Entry(project).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToRoute(new { Controller = "Details", Action = "DetailsProject", id = project.Id });
        }
        #endregion

        //Редактирование данных сотрудника
        #region EditEmployee
        [HttpGet]
        public IActionResult EditEmployee(int id)
        {
            Employee employee = db.Employees.Find(id);

            return View(employee);
        }
        [HttpPost]
        public IActionResult EditEmployee(Employee employee)
        {
            db.Entry(employee).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToRoute(new { Controller = "Details", Action = "DetailsEmployee", id = employee.Id });
        }
        #endregion
    }
}

SibersTestTask/Views/Details/DetailsEmployee.cshtml
@*
    Представление для вывода данных сотрудника    
*@

@model SibersTestTask.Models.Entities.Employee
@{
    ViewBag.Title = Model.SecondName + Model.FirstName + Model.FatherName;
}
<div>
    <a asp-action="Employees" asp-controller="Home" class="btn btn-dark">Back</a>
</div>
<h2>@Model.SecondName @Model.FirstName @Model.FatherName</h2>
<div>
    <a class="btn btn-dark" asp-action="EditEmployee" asp-controller="Edit" asp-route-id="@Model.Id">Edit</a>
    <dl class="dl-horizontal">
        <dt>Id</dt>
        <dd>@Model.Id</dd>

        <dt>Employee name</dt>
        <dd>@Model.SecondName @Model.FirstName @Model.FatherName</dd>

        <dt>Email</dt>
        <dd>@Model.Email</dd>
    </dl>
</div>

SibersTestTask/Views/Details/DetailsProject.cshtml
@*
    Представление для вывода данных проекта
*@

@model SibersTestTask.Models.Entities.Project
@{
    ViewBag.Title = Model.Name;
}
<div>
    <a asp-action="Projects" asp-controller="Home" class="btn btn-dark">Back</a>
</div>
<h2>@Model.Name</h2>
<div>
    <a class="btn btn-dark" asp-action="EditProject" asp-controller="Edit" asp-route-id="@Model.Id">Edit</a>
    <dl class="dl-horizontal">
        <dt>Id</dt>
        <dd>@Model.Id</dd>

        <dt>Project name</dt>
        <dd>@Model.Name</dd>

        <dt>Priority</dt>
        <dd>@Model.Priority</dd>

        <dt>Cutomer company</dt>
        <dd>@Model.CustomerCompany</dd>

        <dt>Contractor company</dt>
        <dd>@Model.ContractorCompany</dd>

        <dt>Project director</dt>
        @* Нахождение руководителя по id и вывод его данных *@
        @foreach (var item in Model.Employees)
        {
            @if (item.Id == Model.DirectorId)
            {
                <dd>@item.SecondName @item.FirstName @item.FatherName</dd>
            }
        }
    </dl>

    @* Вывод данных сотрудников проекта *@
    <dl class="dl-horizontal">
        @if (Model.Employees.Count != 0)
        {
            <dt>Project team</dt>
            @foreach (var item in Model.Employees)
            {
                @if (item.Id != Model.DirectorId)
                {
                    <dd>@item.SecondName @item.FirstName @item.FatherName</dd>
                    <dd><a class="btn btn-dark btn-sm" asp-action="DeleteProjectTeam" asp-controller="Delete" asp-route-idProject="@Model.Id" asp-route-idEmployee="@item.Id">Delete</a></dd>
                }
            }
        }
    </dl>

    @* Добавление сотрудников в проект *@
    <form asp-action="AddEmployeeProject" asp-controller="Add" asp-route-idProject="@Model.Id">
        <div><b>Add new employee to the project</b></div>
        @foreach (var item in ViewBag.Employees)
        {
            @if (item.Id != Model.DirectorId)
            {
                <input type="checkbox" name="selectedEmployees" value="@item.Id" />
                @item.SecondName @item.FirstName @item.FatherName
                <br />
            }
        }
        <p></p>
        <div>
            <input type="submit" value="Add employee" class="btn btn-dark btn-sm" />
        </div>
    </form>
</div>