SibersTestTask/Models/Sort/SortProjectState.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SibersTestTask.Models.Sort
{
    //Критерии проектов для сортировки
    public enum SortProjectState
    {
        NameAsc,
        NameDesc,
        PriorityAsc,
        PriorityDesc,
        CustomerCompanyAsc,
        CustomerCompanyDesc,
        ContractorCompanyAsc,
        ContractorCompanyDesc,
        DirectorAsc,
        DirectorDesc
    }
}

SibersTestTask/Controllers/DetailsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SibersTestTask.Models;
using SibersTestTask.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SibersTestTask.Controllers
{
    public class DetailsController : Controller
    {
        public ProjectContext db;
        public DetailsController(ProjectContext context)
        {
            db = context;
        }

        //Содержимое проекта
        public IActionResult DetailsProject(int id)
        {
            Project project = db.Projects.Include(c => c.Employees).FirstOrDefault(p => p.Id == id);

            if (project != null)
            {
                List<Employee> employees = new List<Employee>();

                //Нахождение сотруников, которых нет в проекте и занесение их в ViewBag
                //В представлении через ViewBag эти сотрудники выводятся, чтобы можно было добавлять новых сотрудников в проект
                bool emp = false;
                foreach (var dbEmployee in db.Employees.ToList())
                {
                    foreach (var team in project.Teams.ToList())
                        if ((team.ProjectId == project.Id) && (team.EmployeeId == dbEmployee.Id))
                            emp = true;

                    if (emp == false)
                        employees.Add(dbEmployee);
                    else
                    emp = false;
                }
                ViewBag.Employees = employees;
                
                return View(project);
            }
            return NotFound();
        }

        //Детали сотрудника
        public IActionResult DetailsEmployee(int id)
        {
            Employee employee = db.Employees.Find(id);

            if (employee != null)
            {
                return View(employee);
            }
            return NotFound();
        }
    }
}

SibersTestTask/Controllers/SortController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SibersTestTask.Models;
using SibersTestTask.Models.Entities;
using SibersTestTask.Models.Sort;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SibersTestTask.Controllers
{
    public class SortController : Controller
    {
        public ProjectContext db;
        public SortController(ProjectContext context)
        {
            db = context;
        }

        //Сортировка проектов
        public async Task<IActionResult> SortProject(SortProjectState sortOrder = SortProjectState.NameAsc)
        {
            IQueryable<Project> projects = db.Projects.Include(p => p.Employees);

            //Переменные для хранения данных проектов
            ViewData["NameSort"] = sortOrder == SortProjectState.NameAsc ? SortProjectState.NameDesc : SortProjectState.NameAsc;
            ViewData["PrioritySort"] = sortOrder == SortProjectState.PriorityAsc ? SortProjectState.PriorityDesc : SortProjectState.PriorityAsc;
            ViewData["CustomerCompanySort"] = sortOrder == SortProjectState.CustomerCompanyAsc ? SortProjectState.CustomerCompanyDesc : SortProjectState.CustomerCompanyAsc;
            ViewData["ContractorCompanySort"] = sortOrder == SortProjectState.ContractorCompanyAsc ? SortProjectState.ContractorCompanyDesc : SortProjectState.ContractorCompanyAsc;
            ViewData["DirectorSort"] = sortOrder == SortProjectState.DirectorAsc ? SortProjectState.DirectorDesc : SortProjectState.DirectorAsc;

            //Сортировка проектов в соответствии с переданным значением
            projects = sortOrder switch
            {
                SortProjectState.NameDesc => projects.OrderByDescending(s => s.Name),
                SortProjectState.PriorityAsc => projects.OrderBy(s => s.Priority),
                SortProjectState.PriorityDesc => projects.OrderByDescending(s => s.Priority),
                SortProjectState.CustomerCompanyAsc => projects.OrderBy(s => s.CustomerCompany),
                SortProjectState.CustomerCompanyDesc => projects.OrderByDescending(s => s.CustomerCompany),
                SortProjectState.ContractorCompanyAsc => projects.OrderBy(s => s.ContractorCompany),
                SortProjectState.ContractorCompanyDesc => projects.OrderByDescending(s => s.ContractorCompany),
                SortProjectState.DirectorAsc => projects.OrderBy(s => s.DirectorId),
                SortProjectState.DirectorDesc => projects.OrderByDescending(s => s.DirectorId),
                _ => projects.OrderBy(s => s.Name)
            };

            return View(await projects.AsNoTracking().ToListAsync());
        }
    }
}

SibersTestTask/Views/Sort/SortProject.cshtml
@*
    Представление для вывода сортируемых данных проектов    
*@

@using SibersTestTask.Models.Entities
@using SibersTestTask.Models.Sort

@model IEnumerable<Project>

@{
    ViewData["Title"] = "Sorting projects";
}
<div><a class="btn btn-dark" asp-action="Projects" asp-controller="Home">Back to the projects</a></div>

<h1>List projects</h1>

<table class="table">
    <tr>
        <th>
            <a asp-action="SortProject" asp-route-sortOrder="@ViewBag.NameSort">Name</a>
        </th>
        <th>
            <a asp-action="SortProject" asp-route-sortOrder="@ViewBag.PrioritySort">Priority</a>
        </th>
        <th>
            <a asp-action="SortProject" asp-route-sortOrder="@ViewBag.CustomerCompanySort">Customer Company</a>
        </th>
        <th>
            <a asp-action="SortProject" asp-route-sortOrder="@ViewBag.ContractorCompanySort">Contractor Company</a>
        </th>
        <th>
            <a  asp-action="SortProject" asp-route-sortOrder="@ViewBag.DirectorSort">Director</a>
        </th>
    </tr>
    @foreach (Project project in Model)
    {
        <tr>
            <td><a asp-action="DetailsProject" asp-controller="Details" asp-route-id="@project.Id">@project.Name</a></td>
            <td>@project.Priority</td>
            <td>@project.CustomerCompany</td>
            <td>@project.ContractorCompany</td>
            <td>
            @foreach (Employee director in project.Employees)
                if (director.Id == project.DirectorId)
                {
                    @director.SecondName
                    @director.FirstName
                    @director.FatherName
                }
            </td>
        </tr>
    }
</table>